GENRE_RULES = [
    {'genre': "Frenchcore", 'rules': {'tempo': {'min': 195}, 'energy': 'high'}},
    {'genre': "Psytrance", 'rules': {'tempo': {'min': 138, 'max': 150}, 'energy': 'high', 'spectral_centroid': {'min': 2600}}},
    {'genre': "Breakbeat", 'rules': {'tempo': {'min': 130, 'max': 150}, 'zero_crossing_rate': {'min': 0.1}}},
    {'genre': "Hard Techno", 'rules': {'tempo': {'min': 145, 'max': 165}, 'energy': 'high'}},
    {'genre': "Techno", 'rules': {'tempo': {'min': 125, 'max': 145}}},
    {'genre': "Experimental", 'rules': {'energy': 'low', 'spectral_centroid': {'max': 1500}}},
    {'genre': "Gabberdisco", 'rules': {'tempo': {'min': 190}, 'energy': 'high', 'spectral_centroid': {'min': 3200}}},
    {'genre': "Hardcore/Gabber", 'rules': {'tempo': {'min': 180}, 'energy': 'high'}},
    {'genre': "Happy Hardcore", 'rules': {'tempo': {'min': 160, 'max': 180}, 'energy': 'high', 'spectral_centroid': {'min': 2800}}},
    {'genre': "Drum & Bass", 'rules': {'tempo': {'min': 170, 'max': 180}, 'zero_crossing_rate': {'min': 0.1}}},
    {'genre': "Trance", 'rules': {'tempo': {'min': 138, 'max': 140}, 'spectral_centroid': {'min': 2500}, 'energy': 'high'}},
    {'genre': "Progressive Trance", 'rules': {'tempo': {'min': 128, 'max': 135}, 'spectral_centroid': {'min': 2500}, 'energy': {'not': 'low'}}},
    {'genre': "Disco House", 'rules': {'tempo': {'min': 120, 'max': 128}, 'spectral_centroid': {'min': 2800}}},
    {'genre': "Jackin' House", 'rules': {'tempo': {'min': 124, 'max': 128}, 'energy': 'high', 'zero_crossing_rate': {'min': 0.09}}},
    {'genre': "Funky House", 'rules': {'tempo': {'min': 125, 'max': 130}, 'energy': {'not': 'low'}, 'spectral_centroid': {'min': 2500}}},
    {'genre': "Tech House", 'rules': {'tempo': {'min': 123, 'max': 128}, 'spectral_centroid': {'min': 2200}, 'zero_crossing_rate': {'min': 0.07}}},
    {'genre': "Soulful House", 'rules': {'tempo': {'min': 120, 'max': 126}, 'energy': {'not': 'high'}, 'spectral_centroid': {'max': 2200}}},
    {'genre': "EDM", 'rules': {'tempo': {'min': 120}, 'spectral_centroid': {'min': 2200}, 'zero_crossing_rate': {'min': 0.08}, 'energy': {'not': 'low'}}},
    {'genre': "Electronic", 'rules': {'spectral_centroid': {'min': 2200}, 'zero_crossing_rate': {'min': 0.08}, 'energy': {'not': 'low'}}},
    {'genre': "EDM", 'rules': [{'tempo': {'min': 140}, 'energy': 'high', 'spectral_centroid': {'min': 2000}}, {'tempo': {'min': 140}, 'energy': 'high', 'zero_crossing_rate': {'min': 0.09}}]},
    {'genre': "Fast Rock", 'rules': {'tempo': {'min': 140}, 'energy': 'high'}},
    {'genre': "Pop", 'rules': {'tempo': {'min': 120, 'max': 140}, 'spectral_centroid': {'min': 2000}}},
    {'genre': "Rock", 'rules': {'tempo': {'min': 120, 'max': 140}}},
    {'genre': "Indie Pop", 'rules': {'tempo': {'min': 90, 'max': 120}, 'spectral_centroid': {'min': 2500}, 'energy': {'not': 'low'}}},
    {'genre': "Alternative Rock", 'rules': {'tempo': {'min': 90, 'max': 120}, 'energy': {'not': 'low'}}},
    {'genre': "Ballad", 'rules': {'tempo': {'min': 90, 'max': 120}, 'energy': 'low'}},
    {'genre': "Ambient", 'rules': {'tempo': {'max': 90}, 'energy': 'low'}},
    {'genre': "Hip-Hop", 'rules': {'tempo': {'max': 90}}},
]