GENRE_RULES = [{'genre': 'Frenchcore', 'rules': {'energy': 'high', 'tempo': {'min': 195}}},
 {'genre': 'Psytrance',
  'rules': {'energy': 'high',
            'spectral_centroid': {'min': 2600},
            'tempo': {'max': 150, 'min': 138}}},
 {'genre': 'Breakbeat',
  'rules': {'tempo': {'max': 150, 'min': 130},
            'zero_crossing_rate': {'min': 0.1}}},
 {'genre': 'Hard Techno',
  'rules': {'energy': 'high', 'tempo': {'max': 165, 'min': 145}}},
 {'genre': 'Techno', 'rules': {'tempo': {'max': 150, 'min': 125}}},
 {'genre': 'Melodic Techno',
  'rules': {'energy': {'not': 'low'},
            'spectral_centroid': {'min': 2300},
            'tempo': {'max': 130, 'min': 120}}},
 {'genre': 'Experimental',
  'rules': {'energy': 'low', 'spectral_centroid': {'max': 1500}}},
 {'genre': 'Gabberdisco',
  'rules': {'energy': 'high',
            'spectral_centroid': {'min': 3200},
            'tempo': {'min': 190}}},
 {'genre': 'Hardcore/Gabber',
  'rules': {'energy': 'high', 'tempo': {'min': 180}}},
 {'genre': 'Happy Hardcore',
  'rules': {'energy': 'high',
            'spectral_centroid': {'min': 2800},
            'tempo': {'max': 180, 'min': 160}}},
 {'genre': 'Drum & Bass',
  'rules': {'tempo': {'max': 180, 'min': 170},
            'zero_crossing_rate': {'min': 0.1}}},
 {'genre': 'Trance',
  'rules': {'energy': 'high',
            'spectral_centroid': {'min': 2500},
            'tempo': {'max': 142, 'min': 135}}},
 {'genre': 'Progressive Trance',
  'rules': {'energy': {'not': 'low'},
            'spectral_centroid': {'min': 2500},
            'tempo': {'max': 135, 'min': 128}}},
 {'genre': 'Disco House',
  'rules': {'spectral_centroid': {'min': 2800},
            'tempo': {'max': 128, 'min': 120}}},
 {'genre': 'Progressive House',
  'rules': {'energy': {'not': 'low'},
            'spectral_centroid': {'min': 2400},
            'tempo': {'max': 130, 'min': 125}}},
 {'genre': "Jackin' House",
  'rules': {'energy': 'high',
            'tempo': {'max': 128, 'min': 124},
            'zero_crossing_rate': {'min': 0.09}}},
 {'genre': 'Funky House',
  'rules': {'energy': {'not': 'low'},
            'spectral_centroid': {'min': 2500},
            'tempo': {'max': 130, 'min': 125}}},
 {'genre': 'Tech House',
  'rules': {'spectral_centroid': {'min': 2200},
            'tempo': {'max': 128, 'min': 123},
            'zero_crossing_rate': {'min': 0.07}}},
 {'genre': 'Soulful House',
  'rules': {'energy': {'not': 'high'},
            'spectral_centroid': {'max': 2200},
            'tempo': {'max': 126, 'min': 120}}},
 {'genre': 'EDM',
  'rules': {'energy': {'not': 'low'},
            'spectral_centroid': {'min': 2200},
            'tempo': {'min': 120},
            'zero_crossing_rate': {'min': 0.08}}},
 {'genre': 'Pop',
  'rules': {'spectral_centroid': {'min': 2000},
            'tempo': {'max': 140, 'min': 100}}},
 {'genre': 'Electronic',
  'rules': {'energy': {'not': 'low'},
            'spectral_centroid': {'min': 2200},
            'zero_crossing_rate': {'min': 0.08}}},
 {'genre': 'EDM',
  'rules': [{'energy': 'high',
             'spectral_centroid': {'min': 2000},
             'tempo': {'min': 140}},
            {'energy': 'high',
             'tempo': {'min': 140},
             'zero_crossing_rate': {'min': 0.09}}]},
 {'genre': 'Fast Rock', 'rules': {'energy': 'high', 'tempo': {'min': 140}}},
 {'genre': 'Rock', 'rules': {'tempo': {'max': 140, 'min': 120}}},
 {'genre': 'Indie Pop',
  'rules': {'energy': {'not': 'low'},
            'spectral_centroid': {'min': 2500},
            'tempo': {'max': 120, 'min': 90}}},
 {'genre': 'Alternative Rock',
  'rules': {'energy': {'not': 'low'}, 'tempo': {'max': 120, 'min': 90}}},
 {'genre': 'Ballad',
  'rules': {'energy': 'low', 'tempo': {'max': 120, 'min': 90}}},
 {'genre': 'Ambient', 'rules': {'energy': 'low', 'tempo': {'max': 90}}},
 {'genre': 'Hip-Hop', 'rules': {'tempo': {'max': 90}}},
 {'genre': 'Gabberdisco', 'rules': {'tempo': {'max': 220, 'min': 180}}},
 {'genre': 'Gabberdisco 180-200bpm',
  'rules': {'tempo': {'max': 200, 'min': 180}}},
 {'genre': 'Hardstyle', 'rules': {'tempo': {'max': 160, 'min': 145}}}]
